CarTool/ViewModels/CarModelViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarTool.ViewModels
{
    public class CarModelViewModel
    {
        public int ModelID { get; set; }
        public int LineID { get; set; }

        [Display(Name = "Line")]
        public string LineName { get; set; }

        [Required(ErrorMessage = "Model name required"), MaxLength(20)]
        [Display(Name = "Name")]
        public string ModelName { get; set; }

        [Required(ErrorMessage = "Description required"), MaxLength(100)]
        [Display(Name = "Description")]
        public string ModelDescription { get; set; }

        public Nullable<int> Price { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Picture required")]
        public byte[] Picture { get; set; }
        public string ImagePath { get; set; }
    }
}

CarTool/Controllers/CarModelsController.cs
using System;
using System.Drawing;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CarTool.Models;
using CarTool.ViewModels;
using System.IO;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Web.Helpers;

namespace CarTool.Controllers
{
    [Authorize]
    public class CarModelsController : Controller
    {
        private CarToolEntities1 db = new CarToolEntities1();

        public ActionResult Index()
        {
            return View();
        }
        // GET: Models
        public ActionResult Models(int page = 1, string search = "")
        {
            int pageSize = 10;
            int totalRecord = 0;
            if (page < 1) page = 1;
            int skip = (page * pageSize) - pageSize;
            var models = GetModels(search, pageSize, out totalRecord);

            foreach(var m in models)
            {
                if (m.Picture == null)
                {
                    // default image
                    m.Picture = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/no_image_selected.png"));
                }
            }
            ViewBag.TotalRows = totalRecord;
            ViewBag.Search = search;
            
            return View("Index", GetCarModelViewModels(models));
        }

        public ActionResult ModelsByLine(int? lineID)
        {
            if (lineID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int totalRecord = 0;
            var models = GetModels("", 10, out totalRecord).Where(m => m.LineID == lineID);

            foreach (var m in models)
            {
                if (m.Picture == null)
                {
                    // default image
                    m.Picture = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/no_image_selected.png"));
                }
            }

            ViewBag.TotalRows = totalRecord;

            return View("Index", GetCarModelViewModels(models));
        }

        public List<Model> GetModels(string search, int pageSize, out int totalRecord)
        {
            var models = (from m in db.Models
                          where
                              m.Description.Contains(search) ||
                              m.Name.Contains(search)
                          select m
                            );
            totalRecord = models.Count();

            return models.ToList();
        }

        // GET: Models/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            if (model.Picture == null)
            {
                // default image
                model.Picture = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/no_image_selected.png"));
            }
            return View(model);
        }

        // GET: Models/Create
        public ActionResult Create()
        {
            ViewBag.LineID = new SelectList(db.Lines, "LineID", "Name");
            return View();
        }

        // POST: Models/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModelID,LineID,Name,Description,Price")] Model model, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if(upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new BinaryReader(upload.InputStream))
                    {
                        model.Picture = reader.ReadBytes(upload.ContentLength);
                    }
                }
                if (model.Picture == null)
                {
                    // default image
                    model.Picture = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/no_image_selected.png"));
                }
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("Models");
            }

            ViewBag.LineID = new SelectList(db.Lines, "LineID", "Name", model.LineID);
            return View(model);
        }

        // GET: Models/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            if (model.Picture == null)
            {
                // default image
                model.Picture = System.IO.File.ReadAllBytes(Server.MapPath("~/Content/no_image_selected.png"));
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ModelID,LineID,Name,Description,Price,Picture")] Model model, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        using (var reader = new BinaryReader(upload.InputStream))
                        {
                            model.Picture = reader.ReadBytes(upload.ContentLength);
                        }
                    }

                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Models");
                }
                catch(Exception ex)
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                }
            }

            return View(model);
        }

        public static void UpdateModelFromViewModel(Model model, CarModelViewModel vm)
        {
            model.Description = vm.ModelDescription;
            model.Name = vm.ModelName;
            model.Price = vm.Price;
            if(!String.IsNullOrEmpty(vm.ImagePath)) // new image selected
            {
                using (MemoryStream stream = new MemoryStream())
                {
                    Image img = Image.FromFile(vm.ImagePath);
                    byte[] newImageBytes;
                    img.Save(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
                    newImageBytes = stream.ToArray();
                    if(newImageBytes.Length > 0)
                    {
                        model.Picture = newImageBytes;
                    }
                }
            }
        }

        // GET: Models/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Models/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Models");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public List<CarModelViewModel> GetCarModelViewModels(IEnumerable<Model> carModels)
        {
            var result = new List<CarModelViewModel>();
            var lines = db.Lines.ToList();

            var query = from m in carModels
                        join l in lines
                            on m.LineID equals l.LineID
                        select new
                        {
                            LineName = l.Name,
                            l.LineID,
                            m.ModelID,
                            ModelName = m.Name,
                            ModelDescription = m.Description,
                            m.Picture,
                            m.Price
                        };

            foreach (var m in query)
            {
                result.Add(new CarModelViewModel
                {
                    ModelID = m.ModelID,
                    LineID = m.LineID,
                    LineName = m.LineName,
                    ModelName = m.ModelName,
                    ModelDescription = m.ModelDescription,
                    Picture = m.Picture,
                    Price = m.Price
                }); ;
            }
            return result;
        }

        public static String ConvertByteArrayToBase64(byte[] picture)
        {
            return Convert.ToBase64String(picture);
        }
    }
}

CarTool/Views/CarModels/Create.cshtml
@model CarTool.Models.Model

@{
    ViewBag.Title = "Create Car Model";
}

<h2>Create</h2>


@using (Html.BeginForm(null, null, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
        <h4>Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LineID, "LineID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LineID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                $@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="upload" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Models")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarTool/Views/CarModels/Delete.cshtml
@model CarTool.Models.Model

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @{
                var base64 = Convert.ToBase64String(Model.Picture);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }

            <img id="currentImage" src="@imgSrc" width="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Line.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Line.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Models")
        </div>
    }
</div>

CarTool/Views/CarModels/Details.cshtml
@model CarTool.Models.Model

@{
    ViewBag.Title = "Model Details";
}

<h2>Model Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @{
                var base64 = Convert.ToBase64String(Model.Picture);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }

            <img src="@imgSrc" width="150" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ModelID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CarTool/Views/CarModels/Edit.cshtml
@model CarTool.Models.Model

@{
    ViewBag.Title = "Edit Car Model";
}

<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Car Model</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ModelID)
    @Html.HiddenFor(model => model.LineID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @{
                var base64 = Convert.ToBase64String(Model.Picture);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            }

            <img id="currentImage" src="@imgSrc" width="150" />
            <input id="upload" name="upload" type="file" />
        </div>
    </div>
 
    <div>
        @Html.HiddenFor(model => model.Picture, new { @id = "picture" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Models")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarTool/Views/CarModels/Index.cshtml
@model IEnumerable<CarTool.ViewModels.CarModelViewModel>
@{
    ViewBag.Title = "Index";

    WebGrid webGrid = new WebGrid(source: Model);
}

<h2>Car Models</h2>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">Search</a>
        </div>
        <div class="collapse navbar-collapse">
            @using (Html.BeginForm("Models", "CarModels", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
            {
                <div class="form-group">
                    <input type="text" name="search" value="@ViewBag.search" class="form-control" placeholder="search" />
                </div>
                <button type="submit" value="Search" class="btn btn-success">Search</button>
            }
        </div>
        <div>
            <p>
                @Html.ActionLink("Create New", "Create")
            </p>
        </div>
    </div>
</nav>

@webGrid.GetHtml(
    htmlAttributes: new { @id = "modelsGrid", @class = "Grid" },
    columns: webGrid.Columns(
        webGrid.Column("ModelName", "Model Name"),
        webGrid.Column("ModelDescription", "Description"),
        webGrid.Column("Price", "Price"),
        webGrid.Column("Picture", format: @<img src="data:image/jpeg;base64,@CarTool.Controllers.CarModelsController.ConvertByteArrayToBase64(item.Picture)" width="150">),
        webGrid.Column("LineName", "Line"),
        webGrid.Column(header: "Edit", format: @<text><a href="~/CarModels/Edit/@item.ModelID">Edit</a></text>),
        webGrid.Column(header: "Details", format: @<text><a href="~/CarModels/Details/@item.ModelID">Details</a></text>),
        webGrid.Column(header: "Delete", format: @<text><a href="~/CarModels/Delete/@item.ModelID">Delete</a></text>)
))